# H2
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/home
    username: sa
    password:
    DB_CLOSE_ON_EXIT: FALSE

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console